---
title: "p8105_hw1_wz2631"
author: "Wenjia Zhu"
date: "2022-09-17"
output: html_document

---
#Here is the solution of problem1.
```{r warning = FALSE}
data("penguins", package = "palmerpenguins")
  head(penguins)
  nrow(penguins)
  ncol(penguins)
  mean(penguins$flipper_length_mm,na.rm = TRUE)
library(ggplot2)
  ggplot(data = penguins, mapping = aes(x = bill_length_mm, y = flipper_length_mm, colour = species)) + geom_point(size = 1)
  ggsave("penguin_flipper_to_bill.png")
```

#Here is the solution of problem2.
```{r}
library(tidyverse)
set.seed(1)
hw1_df <- tibble(
  vec_numeric <- rnorm(10),
  vec_logical <- vec_numeric > 0,
  vec_character <- c(1:10),
  vec_factor <- factor(c("aa","bb","cc","aa","bb","cc","aa","bb","cc","aa"))
)
print(hw1_df)
levels(pull(hw1_df,var = -1))

mean_numeric <- mean(pull(hw1_df,var = 1))  
  mean_numeric
mean_logical <- mean(pull(hw1_df,var = 2))
  mean_logical
mean_character <- mean(pull(hw1_df,var = -2))
  mean_character
mean_factor <- mean(pull(hw1_df,var = -1))
  mean_factor
```

```{r eval = FALSE}
as.numeric(pull(hw1_df,var = 2))
as.numeric(pull(hw1_df,var = -2))
as.numeric(pull(hw1_df,var = -1))
```

